### ISSUE TITLE
How to change the Carousel's control  icon bigger?

### ISSUE THREAD

**Issue by OrNot** [gwtbootstrap3/gwtbootstrap3-demo#107]
In the Demo for Carousel, I want to make the controls  "previous" and "next' bigger.  Is there anyway to config it ?

T.I.A

**Comment by sjardine** [comment]
Sure.  Please look at [Carousel] (http://getbootstrap.com/javascript/#carousel). It should give you enough information on where to start.

**Comment by OrNot** [comment]
Thanks for your reply.  I have checked the link you gave, but I am still not sure how to achieve that for I am not familiar bootstrap at all( also the reason I came to gwtbootstrap ) :(,

Any help will be appreciated.

**Comment by sjardine** [comment]
gwtbootstrap3 requires a knowledge of bootstrap.  It allows you to use bootstrap elements with gwt.  In order to modify the carousel element you will need to modify the css for carousel.

**Comment by OrNot** [comment]
I am reading gwtbootstrap source code.  There is a class named CarouselControl.   Ideally it is good to be allowed to modify the icon size by this class' method. But this class does not provide it. So as a workaround, I can re-write a class named , say, MyCarouselControl and modify the member field Icon by myself. 

How do you think?

thanks
