### ISSUE TITLE
Deploy SNAPSHOT Demo after successful build

### ISSUE THREAD

**Issue by jgodi** [gwtbootstrap3/gwtbootstrap3-demo#65]
It would be nice to have a successful build automatically deploy the SNAPSHOT version of the demo to the gh-pages.

Should be copied/deployed to https://github.com/gwtbootstrap3/gwtbootstrap3-demo/tree/gh-pages/snapshot.

**Comment by ArloL** [comment]
A working example can be seen here:
https://github.com/rgladwell/m2e-android/

The important files are:
https://github.com/rgladwell/m2e-android/blob/master/me.gladwell.eclipse.m2e.android.update/pom.xml
https://github.com/rgladwell/m2e-android/blob/master/.travis.yml#L53

**Comment by jgodi** [comment]
Not sure what is going on. Still getting the:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project gwtbootstrap3-demo: SiteToolException: The site descriptor cannot be resolved from the repository: ArtifactResolutionException: Unable to locate site descriptor: Could not transfer artifact org.gwtbootstrap3:gwtbootstrap3-parent:xml:site_en:0.9-SNAPSHOT from/to sonatype-nexus-snapshots (http://oss.sonatype.org/content/repositories/snapshots): Failed to transfer file: http://oss.sonatype.org/content/repositories/snapshots/org/gwtbootstrap3/gwtbootstrap3-parent/0.9-SNAPSHOT/gwtbootstrap3-parent-0.9-SNAPSHOT-site_en.xml. Return code is: 503 , ReasonPhrase:Service Temporarily Unavailable.
```

error for deploy and site targets. Hmmm

**Comment by crevete** [comment]
I think it issue is resolved by @sjardine.
