### ISSUE TITLE
FlowPanel vs Column: motivation for using FlowPanel into the demo source code

### ISSUE THREAD

**Issue by mickaelbaron** [gwtbootstrap3/gwtbootstrap3-demo#79]
Hi,

Is there a motivation for using FlowPanel compared Column to design an horizontal form ?

Here: https://github.com/gwtbootstrap3/gwtbootstrap3-demo/blob/master/src/main/java/org/gwtbootstrap3/demo/client/application/css/FormsView.ui.xml

```
<b:FormGroup>
  <g:FlowPanel addStyleNames="col-lg-offset-2 col-lg-10">
    <b:CheckBox text="Remember me"/>
  </g:FlowPanel>
</b:FormGroup>
```

We could replace the previous code by this one, no ?
```
<b:FormGroup>
  <b:Column size="LG_10" offset="LG_2">
    <b:CheckBox text="Remember me"/>
  </b:Column>
</b:FormGroup>
```

Mickael

**Comment by jgodi** [comment]
We just try to mimic the Bootstrap demo as much as possible. We could definitely swap something like that.

**Comment by mickaelbaron** [comment]
Thanks for your response

Mickael
