### ISSUE TITLE
Navigation Improvements / Fixes

### ISSUE THREAD

**Issue by p33t** [gwtbootstrap3/gwtbootstrap3-demo#99]
The demo project navigation handling needs some improvements.

**Problems:**
- When on a small device, the NavbarCollapse menu remains on the screen (it should automatically hide)
- Using *PlaceManager.revealPlace()* does NOT trigger a History.valueChange event (which also leaves the scrolling awry)

**Solution:**
- [Tap the NavigationEvent](https://groups.google.com/forum/#!topic/gwt-platform/K8ii4iAYzrM) instead of History.valueChange
- In addition to scrolling to top of page, also collapse the NavbarCollapse if necessary

Sample code (from [a working example](https://subversion.assembla.com/svn/freshcode_public/learn/gwt-bootstrap/src/main/java/biz/freshcode/learn/gwt_bootstrap/client/boot/RootPresenter.java)):
```java
        ... in constructor of presenter or view...
            bus.addHandler(NavigationEvent.getType(), new NavigationHandler() {
                @Override
                public void onNavigation(NavigationEvent navigationEvent) {
                    Scheduler.get().scheduleDeferred(new Command() {
                        @Override
                        public void execute() {
                            // Making the window scroll to top on every page change
                            Window.scrollTo(0, 0);
                            // and collapse any nav menus
                            hideNavbarCollapse();
                        }
                    });
                }
            });
        ...
        }

        private void hideNavbarCollapse() {
            String ariaExpanded = navbarCollapse.getElement().getAttribute("aria-expanded");
            if (Boolean.parseBoolean(ariaExpanded)) {
                navbarCollapse.toggle();
            }
        }
```
Both of these are the result of GWT [awsomeness] doing ajax fetches and not full page fetches.

**Comment by sjardine** [comment]
Would you be willing to submit a PR?

**Comment by p33t** [comment]
Starting process now.  Hopefully will have PR soon.

**Comment by p33t** [comment]
Ugh, sorry.  I accidentally opened another issue #101.
